### ISSUE TITLE
游戏数据异常，检查网络

### ISSUE THREAD

**Issue by Yuanlailai** [MasterHiei/arknights_analysis#39]
![image](https://github.com/MasterHiei/arknights_analysis/assets/46029173/60d0d6b9-60ac-41a5-894d-f1cad50e39b8)
正常网络环境

**Comment by MasterHiei** [comment]
了解🆗 
没匹配新的池子，正在修复。

**Comment by MasterHiei** [comment]
@Yuanlailai 感谢反馈，已在[新版本](https://github.com/MasterHiei/arknights_analysis/releases/latest)中修复 🦖
